### ISSUE TITLE
Issue in Assembly mnemonics

### ISSUE THREAD

**Issue by LV2Code** [lotabout/write-a-C-interpreter#10]
I haven't yet understand so far the use of assembly mnemonics. We are executing source code ( hello.c ) using C functions like printf .

Is there any significance of Assembly instructions or they are just demo purpose. 

I mean if we are just translating source code so the executable C program can run it, why use Assembly to increase overall complexity.

I am not sure am I right or not help me to understand this thing

**Comment by lotabout** [comment]
@LV2Code sorry I did not quite catch what you mean.

Generally, I introduce Assembly instructions for two reasons:
1. It is interpreter that we are building, the assembly instructions are the "syntax" for our virtual machine.
2. The virtual machine just try to simulate what the physical machine, so as to understand how the machine works.

> I mean if we are just translating source code so the executable C program can run it, why use Assembly to increase overall complexity.
By "translating", there should be a target, currently "assembly" is the target. If there is no assembly, what should be your target?

If possible, please describe your question more clearly.

**Comment by Spriithy** [comment]
I think he means, "why generate VM assembly instead of interpreting on the fly".

**Comment by lotabout** [comment]
close due to long time inactivity
