### ISSUE TITLE
&& 运算计算有误

### ISSUE THREAD

**Issue by Hanseltu** [lotabout/write-a-C-interpreter#13]
你好，你的代码写的很漂亮！
我最近在尝试让此解释器运行在64位机器上，在使用你的代码在32位机器上测试时发现‘&&’运算计算有误，不知是我操作有误还是其他原因，目前我也在尝试修改，请问你写完代码后有进行覆盖测试吗？或者有什么其他建议？谢谢。

**Comment by lotabout** [comment]
处理 `&&` 运算符的逻辑是这里

```c
            else if (token == Lan) {
                // logic and
                match(Lan);
                *++text = JZ;
                addr = ++text;
                expression(Or);
                *addr = (int)(text + 1);
                expr_type = INT;
            }
```
注意到 `*addr = (int)(text + 1);` 这里会有一些地址和 int 直接强制转换的过程。如果要跑在 64 位上主要就是要处理地址与整数之间的转换问题。

> 在使用你的代码在32位机器上测试时发现‘&&’运算计算有误

我自己没有 32 位的机器，所以抱歉没法找具体问题

> 你写完代码后有进行覆盖测试吗？

没有，换句话说完成自举就是覆盖测试了。即代码里用到的所有语法都是测试通过的。

> 或者有什么其他建议？

这是本项目的一个 fork，实现了单步调试功能，也许对你 debug 有帮助。
https://github.com/descent/write-a-C-interpreter

**Comment by Hanseltu** [comment]
好的，我再试试，谢谢你！
