### ISSUE TITLE
其中的 *sp++ 的作用是退栈，相当于 POP 操作，这个是不是说反了

### ISSUE THREAD

**Issue by mengyou658** [lotabout/write-a-C-interpreter#34]
https://lotabout.me/2015/write-a-C-interpreter-2/
在 eval() 函数中加入下列代码：
其中的 *sp++ 的作用是退栈，相当于 POP 操作

这个是不是说反了，往栈里面放入数据，是入栈操作

**Comment by liumeng009** [comment]
@mengyou658 "SP 指针寄存器，永远指向当前的栈顶。注意的是由于栈是位于高地址并向低地址增长的，所以入栈时 SP 的值减小。"
*sp取出栈顶的值后，由于是向低地址增长（也就是--代表增长）sp++代表踢出栈顶元素，也就是退栈

**Comment by mengyou658** [comment]
谢谢啦
