### ISSUE TITLE
c没有getline

### ISSUE THREAD

**Issue by liumeng009** [lotabout/write-a-C-interpreter#35]
int getline(char * src){    
    char ch;                            //保存单个字符的变量 
    while ((ch = getchar()) && ch != 0 && ch != '\n'){
        *src++ = ch;
    }
    *src = 0;           //结尾放入EOF，字符串构造完毕
}

**Comment by cupen** [comment]
@liumeng009  忍不了,  帮你弄了下格式. 
```c
int getline(char * src){
    char ch; //保存单个字符的变量
    while ((ch = getchar()) && ch != 0 && ch != '\n'){
        *src++ = ch;
    }
    *src = 0; //结尾放入EOF，字符串构造完毕
}
```

**Comment by lotabout** [comment]
这段代码是用来解决什么问题？

**Comment by liumeng009** [comment]
> @liumeng009 这段代码是用来解决什么问题？
你好，我在windows下mingw-gcc没有getline函数，在此补充一下
