### ISSUE TITLE
hash = hash * 147 + *src

### ISSUE THREAD

**Issue by lympassion** [lotabout/write-a-C-interpreter#41]
Hello! It's  an honor to find you guys' code about compile and lexier. And this is an excellent work. But There is a problem when I read your code. it is about parsing identifier, the hash.
this line: hash = hash * 147 + *src;
why you chose the number 147? I wonder. and can this decrease conflict among different identifiers?
Looking forward to your reply.

**Comment by lotabout** [comment]
@lympassion Sorry for late reply.

It was copied from [c4](https://github.com/rswier/c4/blob/master/c4.c#L73). And I don't know if it has special meaning. Normally a prime number should be preferred for decreasing conflict.
