### ISSUE TITLE
multiple assignment of ax

### ISSUE THREAD

**Issue by knavels** [lotabout/write-a-C-interpreter#46]
Hello

I noticed this question seemed to be asked before in Chinese but unfortunately I couldn't get precise translation of the answers, why we need to do `ax = *(char *)*sp++ = ax;` while if we remove `ax =` from the beginning the answer should not change, please correct me if I'm wrong, why we need this? thanks

**Comment by lotabout** [comment]
No big difference, you could remove the first assignment.

**Comment by BreakingLead** [comment]
but why do this?
