### ISSUE TITLE
赋值问题

### ISSUE THREAD

**Issue by sundyloveme** [lotabout/write-a-C-interpreter#5]
请问，这个编译器是如何解析 `i=10` 的呢？这个赋值操作怎么实现的呢？ 有看到将`Name`写入`Symbol`中；但是并没有看到将 `10` 写入`Symbol`中的 `Value`啊。
望解解答。谢谢。

**Comment by lotabout** [comment]
@sundyloveme 首先，编译器有两种语法，一种是定义 `int i;` 一种是赋值 `i = 10;`。但是大家常用的初始化 `int i = 10;` 是不支持的。

你说的将 Name 写入 Symbol 中是解决处理 “定义” 的问题。赋值相关的代码则参见 https://github.com/lotabout/write-a-C-interpreter/blob/master/xc-tutor.c#L578

**Comment by sundyloveme** [comment]
但是在函数体内的`int i = 10;`是支持的吧？因为我看到你的测试用例里面有的。

**Comment by sundyloveme** [comment]
感谢你的回答，也看了你的链接。其实我就是想知道`Symbol`表中的`Token, Hash, Name, Type, Class, Value, BType, BClass, BValue, IdSizez`中的`Value`是怎么被写入的，因为它存放着这个变量的值嘛。

**Comment by lotabout** [comment]
@sundyloveme 其实它存放的并 *不是* 变量的值。对于不同的类型，存放的内容是不同的，例如对于 `enum {FIRST = 1}` 对于 `FIRST` 它存放的的确是对应的值 `1`。但对于全局变量来说，存放的是该变量在 `data` 段的 [地址](https://github.com/lotabout/write-a-C-interpreter/blob/master/xc-tutor.c#L1176)。对于局部变量而言，存放的是该变量在栈上的 [相对位置](https://github.com/lotabout/write-a-C-interpreter/blob/master/xc-tutor.c#L1029)

所以它存放的是关于 “标识符” 的信息，不同的标识符的 “值” 有着不同的定义。
