### ISSUE TITLE
SI与SC指令

### ISSUE THREAD

**Issue by piaopiao9393** [lotabout/write-a-C-interpreter#8]
博客第二节中，讲了SI与SC指令，实现如下：
```c
void eval() {
    int op, *tmp;
    while (1) {
        if (op == IMM)       {ax = *pc++;}                                     // load immediate value to ax
        else if (op == LC)   {ax = *(char *)ax;}                               // load character to ax, address in ax
        else if (op == LI)   {ax = *(int *)ax;}                                // load integer to ax, address in ax
        else if (op == SC)   {ax = *(char *)*sp++ = ax;}                       // save character to address, value in ax, address on stack
        else if (op == SI)   {*(int *)*sp++ = ax;}                             // save integer to address, value in ax, address on stack
    }
```

关于SC的实现： `ax=*(char*)*sp++=ax;` 这一句我理解是：
ax中原本存放地址，将其存入栈顶中，然后取出栈顶保存地址对应的值，再赋值给ax，出栈。请问我的理解对吗？
另外，我觉得SC与SI是相似的操作，为什么SC是 `ax = *(char *)*sp++ = ax` 而SI却是 `*(int *)*sp++ = ax` 呢？

**Comment by lotabout** [comment]
@piaopiao9393 
首先，你对实现的理解有误，在博客里写的是
> `SC` 将 `ax` 中的数据作为字符存放入地址中，要求栈顶存放地址。
这点你可以再理解一下。

> 我觉得SC与SI是相似的操作，为什么SC是 ax = *(char *)*sp++ = ax 而SI却是 *(int *)*sp++ = ax 呢？
这里我先卖个关子，在你理解了上面这点之后看能不能理解，我晚上来回答，期间加油思考哈 :)

**Comment by lotabout** [comment]
最后来说一下为什么 `SC` 与 `SI` 的实现有区别。区别是 `SC` 最后把 `char` 类型的结果又重新赋值到 `ax` 上。

让我们假设由于某种原因， `ax` 里存放的并不是一个 `char` 类型的数据，假如，是 `300` 那么执行完 `SC` 后，不同的实现得到的结果会有什么不同呢？

所以 `SC` 的实现里，额外的赋值操作的作用是确保操作结束后， `ax` 中存放的是正确的 `char` 类型的值。

**Comment by piaopiao9393** [comment]
@lotabout 
你好，这是我对该问题的思考:
/*
 ax:通用寄存器
 sp：指向当前栈顶
 SC:将ax中的数据作为字符放入地址中，要求栈顶存放地址(以栈顶为地址存char数并弹栈)
*/

ax = *(char *)*sp++ = ax;

/*
 注：ax初始存放的是char类型数据。
 这个语句分解如下：
  忽略++，化简等式：
  ax = *(char *)*sp = ax;
  看右边的等式：
  char* temp = (char*)*sp // 这句将栈顶元素强制转换为char类型指针
  *temp = ax; //栈顶元素所指向的地址存放char类型ax的值。
  sp++；//出栈
  现在看等式左边：
  ax = *temp;//栈顶元素做地址，取出其值给ax。
 通过我的语句分解有以下结论：
 1.右边这个等式作用是：把char型ax的值赋值给栈顶元素所指向的地址空间之中。
 2.左边这个等式：将弹栈后新的栈顶所指向内存空间的值赋给ax，但这个值是int型还是char型我们并不知道。
 3.疑问1：在我的理解中，弹栈操作是sp++，而博文中弹栈是*sp++。
 4.接着问题3，经过*(char *)*sp=ax;后，相当于*sp保存了栈顶指针的值，它是一个地址，该地址存放的值是ax的值。但是随后的sp++操作出栈后，这个保存的地址也没有了，那怎么办呢？
 5.对于SC操作，假设ax最初存放的是整型数据300，那么请看右边等式*(char*)*sp++=ax,(char*)类型的指针应该是不可以指向整型数据的，这个时候会报错。还是不理解左边ax的意义。
*/
有自己的理解也有新的问题，请指教，谢谢！

**Comment by lotabout** [comment]
@piaopiao9393 你拆解的这部分是不全对

```
char temp = (char *)*sp // 这句将栈顶元素强制转换为char类型指针
// 上面这句不知是否笔误，正确应该是 char * temp = (char *)*sp;
temp = ax; //栈顶元素所指向的地址存放char类型ax的值。
// 同上，应为 *temp = ax;
sp++；//出栈
ax = temp;//栈顶元素做地址，取出其值给ax。
// 因此，这里是 ax = *temp;
```

所以你的这个理解 `2.左边这个等式：将弹栈后新的栈顶所指向内存空间的值赋给ax` 是不对的。

到这里我依旧先打住，你可以先根据我上面给出的解释再想想看。

**Comment by piaopiao9393** [comment]
ax = *(char *)*sp++=ax;
/*
	对上面语句重新分解：
	先看右边（忽略++）：
		char* temp = (char*)*sp;//将栈顶地址指向的内存空间转换为char*类型。
		*temp = ax;//把ax中存储的值赋值给栈顶指针指向的内存空间。
		sp++；//出栈，这里我仍理解sp++为出栈，但博客中*sp++为出栈。
	再看左边：
		ax = *temp;//把原栈顶指针的值赋值给通用寄存器。
	关于SC与SI区别的理解：
	我们仍假设ax中存放的是int型整数300，下边是我在vs2015的测试代码：
		void main() {
			int stack[2] = { 0 };
			char* temp = &stack[1];
			int ax = 300;
			*temp = ax;
			ax = *temp;
			return;
		}
	测试过后，没又报错，是不是我理解错了？	
*/

**Comment by lotabout** [comment]
@piaopiao9393 你查看来最后 `ax` 的值是什么，还是 300 吗？

P.S. 代码最好用 markdown 的语法包起来，这样能有高亮，好看点。

**Comment by piaopiao9393** [comment]
@lotabout 
我查看了ax的值，ax的值原本为300，在上面那个例子中变为57。发现如果SC操作与SI操作不同的地方在于SC要有一次int转为char的转换，通过查找ASCII表完成。如果ax的值大于127的话，会出现赋值错误。而SC将char类型返回赋值给int类型ax，可以检查两次ax的值是否相等的方式判断SC是否操作成功。
关于*sp++是出栈的问题，我还是不理解，寄存器的声明如下：
`int *pc, *sp, *bp, ax, cycle;`
可以看出，sp++才是出栈操作，博客上写的“*sp++的作用是退栈，相当于POP操作”，这个我不太理解。

**Comment by lotabout** [comment]
@piaopiao9393 你的理解是正确的， `sp++` 才是出栈。博客里是笔误。

**Comment by piaopiao9393** [comment]
@lotabout 
都明白了，感谢！
