### ISSUE TITLE
Getting warning

### ISSUE THREAD

**Issue by LV2Code** [lotabout/write-a-C-interpreter#9]
![warning](https://user-images.githubusercontent.com/20240501/30195221-a9f77e74-9475-11e7-8566-1e72b112342d.png)

Hi getting warning and no further process after that, working on 64-bit windows machin

**Comment by lotabout** [comment]
@LV2Code 
The command `gcc -o xc xc.c` just compile the source code `xc.c` to executable `xc`.

Next, please try (either one) of the commands to play:
```
./xc hello.c
./xc -s hello.c

./xc xc.c hello.c
./xc xc.c xc.c hello.c
```

**Comment by LV2Code** [comment]
Thanks bro, I was stopped at the warning but it works Perfect !
